# Generated by Django 5.2 on 2025-04-02 16:08

from django.db import migrations, models
import django.db.models.deletion


def link_to_primary_networks(apps, schema_editor):
    Network = apps.get_model('api', 'Network')
    CertificateAuthority = apps.get_model('api', 'CertificateAuthority')
    Lighthouse = apps.get_model('api', 'Lighthouse')
    Node = apps.get_model('api', 'Node')

    for ca in CertificateAuthority.objects.all():
        network = Network.objects.get(organization=ca.organization, is_primary=True)
        ca.network = network
        ca.save()

    for lighthouse in Lighthouse.objects.all():
        network = Network.objects.get(organization=lighthouse.organization, is_primary=True)
        lighthouse.network = network
        lighthouse.save()

    for node in Node.objects.all():
        network = Network.objects.get(organization=node.organization, is_primary=True)
        node.network = network
        node.save()


def reverse_link_to_primary_networks(apps, schema_editor):
    CertificateAuthority = apps.get_model('api', 'CertificateAuthority')
    Lighthouse = apps.get_model('api', 'Lighthouse')
    Node = apps.get_model('api', 'Node')

    CertificateAuthority.objects.all().update(network=None)
    Lighthouse.objects.all().update(network=None)
    Node.objects.all().update(network=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_primary_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='network',
            field=models.ForeignKey(null=True, limit_choices_to={'is_primary': True}, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_authority', to='api.network'),
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.network'),
        ),
        migrations.AddField(
            model_name='node',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.network'),
        ),
        migrations.RunPython(link_to_primary_networks, reverse_link_to_primary_networks),
        migrations.AlterField(
            model_name='certificateauthority',
            name='network',
            field=models.ForeignKey(limit_choices_to={'is_primary': True}, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_authority', to='api.network'),
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.network'),
        ),
        migrations.AlterField(
            model_name='node',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.network'),
        ),
    ] 