# Generated by Django 5.2 on 2025-04-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_network_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lighthouse",
            name="nebula_ip",
            field=models.GenericIPAddressField(
                blank=True,
                null=True,
                protocol="IPv4",
                unique=True,
                verbose_name="Nebula IP",
            ),
        ),
        migrations.AlterField(
            model_name="lighthouse",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.network",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="nebula_ip",
            field=models.GenericIPAddressField(
                blank=True,
                null=True,
                protocol="IPv4",
                unique=True,
                verbose_name="Nebula IP",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.network",
            ),
        ),
    ]
