# Generated by Django 5.2 on 2025-04-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lighthouse_nebula_ip_alter_lighthouse_network_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lighthouse',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterField(
            model_name='lighthouse',
            name='nebula_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Nebula IP'),
        ),
        migrations.AlterField(
            model_name='node',
            name='nebula_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Nebula IP'),
        ),
        migrations.AlterUniqueTogether(
            name='lighthouse',
            unique_together={('organization', 'name'), ('organization', 'nebula_ip')},
        ),
    ]
