# Generated by Django 5.2 on 2025-04-03 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_lighthouse_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP"),
                            ("udp", "UDP"),
                            ("icmp", "ICMP"),
                            ("any", "Any"),
                        ],
                        max_length=4,
                    ),
                ),
                ("port", models.IntegerField(blank=True, null=True)),
                ("cidr", models.CharField(blank=True, max_length=18, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenced_by_rules",
                        to="api.securitygroup",
                    ),
                ),
                (
                    "security_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firewall_rules",
                        to="api.securitygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "firewall rule",
                "verbose_name_plural": "firewall rules",
            },
        ),
    ]
