# Generated by Django 5.2 on 2025-04-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_firewallrule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lighthouse",
            unique_together={("organization", "name")},
        ),
    ]
