# Generated by Django 5.2 on 2025-04-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_fix_lighthouse_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallrule",
            name="ca_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="firewallrule",
            name="ca_sha",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="firewallrule",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="referenced_by_rules_many",
                to="api.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="firewallrule",
            name="host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="firewallrule",
            name="local_cidr",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="firewallrule",
            name="port",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
